catcollector/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
    # path('/users/, view.get_user, name='get_users') # this would handle Index show All user,  Post to create a new user
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('about/', views.about, name='about'),
    path('cats/me', views.my_cats_index, name="my-cats"),
    path('cats/', views.CatList.as_view(), name='cat-index'),
    path('cats/create', views.CatCreate.as_view(), name='cat-create' ),
    path('cats/<int:pk>', views.cat_detail, name='cat-detail'),
    path('cats/<int:cat_id>/add-feeding/', views.add_feeding, name='add_feeding'),
    path('cats/<int:cat_id>/associate-toy/<int:toy_id>', views.associate_toy, name='associate-toy'),
    path('cats/<int:pk>/update', views.CatUpdate.as_view(), name='cat-update'),
    path('cats/<int:pk>/delete', views.CatDelete.as_view(), name='cat-delete'),
    path('toys/create', views.ToyCreate.as_view(), name='toy-create'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toy_detail'),
    path('toys/<int:pk>/update', views.ToyUpdate.as_view(), name='toy-update'),
    path('toys/<int:pk>/delete', views.ToyDelete.as_view(), name='toy-delete'),
    path('toys/', views.ToyList.as_view(), name='toy-index'),
]

main_app/models.py
# This has instructions on how to be a django model
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("toy_detail", kwargs={"pk": self.pk})

# we make a new class and inherit all those django model instructions
class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toy = models.ManyToManyField(Toy) #should have been toys
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"A Cat named {self.name} that is {self.age} years old."
    
    def get_absolute_url(self):
        return reverse('cat-detail', kwargs={'pk': self.id})
    
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
)
    
class Feeding(models.Model):
    date = models.DateField("Feeding Date")
    meal = models.CharField(
        verbose_name="Meal:",
        max_length=1,
        choices=MEALS, # this works like a enum and provides choices
        default=MEALS[0][0] 
        ) # (B,L,D Breakfast, Lunch, Dinner)
    
    # setting up a relationship - one to many
    # we can use the models.ForeignKey(Table_To_Ref, on_delete=models.cascade
    # models.CASCADE tells django if the parent cat is deleted, 
    # then delete all the related feedings to that cat
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE, related_name='feedings')
    # this Feeding will show up under the cat on feeding_set  or modelName_set

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm, DateInput
from .models import Feeding


class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal'] # or something like "__all__"
        widgets = {
            'date': DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': "Select A Date",
                    'type': 'date'
                }
            )
        }
        

main_app/views.py
from django.shortcuts import render, redirect
from .models import Cat, Toy # * imports everything
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import FeedingForm
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# class Cat:
#     def __init__(self, name, breed, description, age):
#         self.name = name
#         self.breed = breed
#         self.description = description
#         self.age = age

# # Create a list of Cat instances
# cats = [
#     Cat('Lolo', 'tabby', 'Kinda rude.', 3),
#     Cat('Sachi', 'tortoiseshell', 'Looks like a turtle.', 0),
#     Cat('Fancy', 'bombay', 'Happy fluff ball.', 4),
#     Cat('Bonk', 'selkirk rex', 'Meows loudly.', 6)
# ]


# def home(request):
#     return render(request, 'home.html')

class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def cat_index(request, pk):
    cats = Cat.objects.all()
    cats = Cat.objects.all(pk)
    return render(request, 'cats/detail.html', {
        'cat': cats,
    })

@login_required
def my_cats_index(request):
    #Filter to only show the users cats
    cats = Cat.objects.filter(user=request.user)
    return render(request, 'cats/index.html', {'object_list': cats})

@login_required
def cat_detail(request, pk):
    cats = Cat.objects.get(id=pk)
    feeding_form = FeedingForm() # new instance of the form
    toys = Toy.objects.exclude(id__in = cats.toy.all().values_list('id'))

    return render(request, 'cats/detail.html', {
        'cat': cats,
        'feeding_form': feeding_form, # pass the form to the template
        'toys': toys # this should show toys the cat does not own
    })

@login_required
def add_feeding(request, cat_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = cat_id
        new_feeding.save()
    return redirect('cat-detail', pk=cat_id)

@login_required
def associate_toy(request, cat_id, toy_id):
    Cat.objects.get(id=cat_id).toy.add(toy_id)
    return redirect('cat-detail', pk=cat_id)

@login_required
def remove_toy(request, cat_id, toy_id):
    cat = Cat.objects.get(id=cat_id)
    cat.toy.remove(toy_id)
    return redirect('cat-detail', cat_id=cat.id)

# CBV Class Based Views

'''
ListView - list stuff
CreateView - create stuff
DeleteView - delete stuff
UpdateView - update stuff
DetailView - show page
'''

# Listing
class CatList(ListView):
    model = Cat
    template_name = 'cats/index.html'


class CatCreate(CreateView):
    model = Cat
    # Lets createview know which fields to use
    # fields = '__all__'
    # or a list
    fields = ['name', 'breed', 'description', 'age']
    # success_url='/cats/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

# Detail
class CatDetail(DetailView):
    model = Cat
    template_name='cats/detail.html'

# Delete
class CatDelete(DeleteView):
    model=Cat
    success_url='/cats'

# Update
class CatUpdate(UpdateView):
    model=Cat
    fields=['breed', 'description', 'age']


# Get /toy/create and Post /toy/create
class ToyCreate(CreateView):
    model = Toy
    fields= "__all__"

class ToyDetail(DetailView):
    model = Toy
    template_name = 'toys/detail.html'

class ToyList(ListView):
    model = Toy
    template_name = 'toys/index.html'

class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

def signup(request):
    error_message = ''

    # request has a "method" on it was can use to check what type of request this is
    if request.method == "POST":
        # request also as request.POST === req.body
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # save this user is the form is valid
            user = form.save()
            # Login a user using the login method from django auth
            login(request, user)
            # redirect to the index page
            return redirect('cat-index')
        else:
            error_message = "Invalid sign up - try again"

    form = UserCreationForm()
    return render(request, 'signup.html', {
        'form': form,
        'error_message': error_message
    })

main_app/templates/about.html
{% extends "base.html"%}
{% block content %}
<h1>About the Cat Collector</h1>
<hr />
<p class="page-content">
  I like long romantic walks down the produce aisle!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'images/splash.svg' %}"
    />
    <title>Cat Collector</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    {% block head %} {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img
            src="{% static 'images/header-logo.svg' %}"
            alt="The Cat Collector Logo"
          />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'cat-index' %}">All Cats</a></li>
          <li><a href="{% url 'my-cats' %}">My Cats</a></li>
          <li><a href="{% url 'toy-index' %}">All Toys</a></li>
          <li><a href="{% url 'cat-create' %}">Add a Cat</a></li>
          <li><a href="{% url 'toy-create' %}">Add a Toy</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit">Log out</button>
            </form>
          </li>
          {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
{% endblock %}
{% block content %}
<section class="cat-container">
    <div class="cat-img">
        <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
    </div>
    <div class="cat-details">
        <h1>{{ cat.name }}</h1>
        {% if cat.age > 0 %}
        <h2>A {{ cat.age }} year old {{ cat.breed }}</h2>
        {% else %}
        <h2>A {{ cat.breed }} kitten.</h2>
        {% endif %}
        <p>{{ cat.description }}</p>
    </div>
</section>
<div class="cat-action">
    <a href="{% url 'cat-update' cat.id %}" class="btn warn">Edit</a>
    <a href="{% url 'cat-delete' cat.id %}" class="btn danger">Delete</a>
</div>

<!-- Existing cat-container above -->
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
      <img
        src="{% static 'images/cat-cone.svg' %}"
        alt="An ice cream cone cat"
      />
      <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
      <img
        src="{% static 'images/kitty-kabob.svg' %}"
        alt="A kabob of kittens"
      />
    </div>
        <form action="{% url 'add_feeding' cat.id %}" method="post">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <button type="submit" class="btn submit">Add Feeding</button>

        </form>
        {% if cat.feedings.all.count %}

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feedings.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="subsection-content">
      <p>⚠️ {{cat.name}} has not been fed!</p>
    </div>
    {% endif %}
  </section>
</div>

<section class="feedings">
  <!-- This is a long section -->
</section>

<section class="toys">
  <div class="subsection-title">
    <h2>Toys</h2>
    <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
    <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
    <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" />
  </div>

<h3>Available Toys</h3>
  <div class="subsection-content">
  {% if toys.count %} 
    {% for toy in toys.all %}
      <div class="toy-container">
        <div class="color-block" style="background-color: {{ toy.color }}"></div>
        <a href="{% url 'toy_detail' toy.id %}">
          <p>A {{ toy.color }} {{ toy.name }}</p>
        </a>
        <form action="{% url 'associate-toy' cat.id toy.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn submit">Give toy</button>
        </form>
      </div>
    {% endfor %} 
  {% else %}
    <p class="all-toys">{{cat.name}} already has all the available toys 🥳</p>
  {% endif %}
</div>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-index.css' %}" />
{% endblock %}

{% block content %}

<section class="page-header">
    <h1>Cat List</h1>
    <img src="{% static 'images/cool-cat.svg' %}" alt="A cool cat" />
    <img src="{% static 'images/happy-cat.svg' %}" alt="A happy cat" />
    <img src="{% static 'images/teacup-cat.svg' %}" alt="A cat in a teacup" />
    <img src="{% static 'images/cat-in-box.svg' %}" alt="A cat in a box" />
</section>

<section class="card-container">
    {% for cat in object_list %}
    <a href="{% url 'cat-detail' cat.id %}">
        <div class="card">
            <div class="card-content">
                <div class="card-img-container">
                    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
                </div>
                <h2 class="card-title">{{ cat.name }}</h2>
                {% if cat.age > 0 %}
                <p>A {{ cat.age }} year old {{ cat.breed }}</p>
                {% else %}
                <p>A {{ cat.breed }} kitten.</p>
                {% endif %}
                <p><small>{{ cat.description }}</small></p>
            </div>
        </div>
    </a>

    {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img
      src="{% static 'images/splash.svg' %}"
      alt="The Cat Collector Cat"
    />
  </div>
  <img
    src="{% static 'images/logotype.svg' %}"
    alt="Text reads: Cat Collector"
  />
</section>

{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}
{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Cat?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete {{ cat.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'cat-detail' cat.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}

<div class="page-header">
    {% if object %}
    <h1>Edit {{ object.name }}</h1>
    {% else %}
    <h1>Add a Cat</h1>
    {% endif %}

    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/cat_list.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-index.css' %}" />
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Cat List</h1>
  <img src="{% static 'images/cool-cat.svg' %}" alt="A cool cat" />
  <img src="{% static 'images/happy-cat.svg' %}" alt="A happy cat" />
  <img src="{% static 'images/teacup-cat.svg' %}" alt="A cat in a teacup" />
  <img src="{% static 'images/cat-in-box.svg' %}" alt="A cat in a box" />
</section>

<section class="card-container">
  {% for cat in cats %}
  <div class="card">
    <div class="card-content">
      <div class="card-img-container">
        <img
          src="{% static 'images/sk8r-boi-cat.svg' %}"
          alt="A skater boy cat"
        />
      </div>
      <h2 class="card-title">{{ cat.name }}</h2>
      {% if cat.age > 0 %}
      <p>A {{ cat.age }} year old {{ cat.breed }}</p>
      {% else %}
      <p>A {{ cat.breed }} kitten.</p>
      {% endif %}
      <p><small>{{ cat.description }}</small></p>
    </div>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %} {% block content %} 

<h1>Do you want to delete <span class="red-text">{{toy.name}}</span></h1>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes Delete this Toy" class="btn"/>
  <a href="{% url 'toy_detail' toy.id%}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Toy</h1>
    {% endif %}
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/toys/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/toys/toy-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card" style="border-color: {{ toy.color }}">
  <div class="card-bg" style="background-color: {{ toy.color }}"></div>
  <div class="card-content">
    <h2>{{ toy.name }}</h2>
    <p>A {{ toy.color }} toy</p>
  </div>
</div>
<a href="{% url 'toy-update' toy.id %}" class="btn warn">Edit</a>
<a href="{% url 'toy-delete' toy.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/toys/toy-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Cat Toys</h1>
  <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
  <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
  <img src="{% static 'images/post.svg' %}" alt="A scratching post" />
  <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" />
</section>

<section class="card-container">
  {% for toy in toy_list %}
    <div class="card" style="border-color: {{ toy.color }}">
      <div class="card-bg" style="background-color: {{ toy.color }}"></div>
      <a href="{% url 'toy_detail' toy.id %}">
        <div class="card-content">
          <h2>{{ toy.name }}</h2>
          <p>A {{ toy.color }} toy</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}